# Generated by Django 4.2.27 on 2026-02-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_article_uploaded_at_alter_article_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="شماره دانشجویی"
            ),
        ),
    ]
