# Generated by Django 4.2.27 on 2026-02-19 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_student_student_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="about_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="درباره کنفرانس"
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="acceptance_notification",
            field=models.DateField(
                blank=True, null=True, verbose_name="اعلام نتایج داوری"
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="registration_deadline",
            field=models.DateField(
                blank=True, null=True, verbose_name="مهلت ثبت نام نهایی"
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="submission_deadline",
            field=models.DateField(
                blank=True, null=True, verbose_name="مهلت ارسال مقالات"
            ),
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="core.conference",
                    ),
                ),
            ],
            options={"verbose_name_plural": "News",},
        ),
    ]
