# Generated by Django 4.2.27 on 2026-02-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_conference_about_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="conference", name="about_text",),
        migrations.RemoveField(model_name="conference", name="brochure_info",),
        migrations.RemoveField(model_name="conference", name="sponsors",),
        migrations.AddField(
            model_name="conference",
            name="guide_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="guides/",
                verbose_name="فایل راهنمای نگارش",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="is_scientific_committee",
            field=models.BooleanField(default=False, verbose_name="عضو کمیته علمی"),
        ),
        migrations.AddField(
            model_name="professor",
            name="rank",
            field=models.CharField(
                choices=[
                    ("prof", "استاد تمام"),
                    ("assoc_prof", "دانشیار"),
                    ("assist_prof", "استادیار"),
                    ("lecturer", "مربی"),
                ],
                default="assist_prof",
                max_length=20,
                verbose_name="رتبه علمی",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="university",
            field=models.CharField(blank=True, max_length=200, verbose_name="دانشگاه"),
        ),
        migrations.AlterField(
            model_name="conference",
            name="acceptance_notification",
            field=models.DateField(blank=True, null=True, verbose_name="اعلام نتایج"),
        ),
        migrations.AlterField(
            model_name="conference",
            name="registration_deadline",
            field=models.DateField(
                blank=True, null=True, verbose_name="ثبت\u200cنام نهایی"
            ),
        ),
        migrations.AlterField(
            model_name="conference",
            name="submission_deadline",
            field=models.DateField(
                blank=True, null=True, verbose_name="مهلت ارسال مقاله"
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="bio",
            field=models.TextField(blank=True, verbose_name="بیوگرافی"),
        ),
    ]
