# Generated by Django 4.2.27 on 2026-02-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_conference_about_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="topics",
            field=models.TextField(
                blank=True,
                help_text="هر محور را با خط تیره جدا کنید",
                null=True,
                verbose_name="محورهای کنفرانس",
            ),
        ),
    ]
