# Generated by Django 4.2.27 on 2026-02-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_conference_topics"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="نام سازمان/شرکت"),
                ),
                ("logo", models.ImageField(upload_to="sponsors/", verbose_name="لوگو")),
                (
                    "link",
                    models.URLField(
                        blank=True, null=True, verbose_name="لینک وب\u200cسایت حامی"
                    ),
                ),
            ],
            options={"verbose_name": "حامی", "verbose_name_plural": "حامیان",},
        ),
    ]
