# Generated by Django 4.2.27 on 2026-02-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_sponsor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="عنوان محور (مثلاً هوش مصنوعی)"
                    ),
                ),
                (
                    "icon_code",
                    models.CharField(
                        help_text="از نام\u200cهای Lucide یا Emoji استفاده کنید",
                        max_length=50,
                        verbose_name="کد آیکون (مثلاً cpu یا network)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیحات کوتاه"),
                ),
            ],
            options={
                "verbose_name": "محور تخصصی",
                "verbose_name_plural": "محورهای تخصصی",
            },
        ),
    ]
