# Generated by Django 4.2.27 on 2026-02-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_topic"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="سوال")),
                ("answer", models.TextField(verbose_name="پاسخ")),
            ],
            options={
                "verbose_name": "سوال متداول",
                "verbose_name_plural": "سوالات متداول",
            },
        ),
    ]
