# Generated by Django 4.2.27 on 2026-02-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام سخنران")),
                (
                    "designation",
                    models.CharField(max_length=200, verbose_name="عنوان علمی/شغلی"),
                ),
                (
                    "university",
                    models.CharField(max_length=200, verbose_name="دانشگاه/موسسه"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="speakers/", verbose_name="تصویر"),
                ),
                (
                    "topic",
                    models.CharField(max_length=255, verbose_name="موضوع سخنرانی"),
                ),
            ],
        ),
    ]
