# Generated by Django 4.2.27 on 2026-02-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_speaker"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tracking_code",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=12,
                null=True,
                unique=True,
                verbose_name="کد رهگیری",
            ),
        ),
    ]
