# Generated by Django 4.2.27 on 2026-02-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_article_tracking_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="professor_comment",
            field=models.TextField(blank=True, null=True, verbose_name="نظر استاد"),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در حال داوری"),
                    ("accepted", "پذیرفته شده"),
                    ("rejected", "نیاز به اصلاح"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
