# Generated by Django 4.2.27 on 2026-02-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_payment"),
    ]

    operations = [
        migrations.RemoveField(model_name="payment", name="is_verified",),
        migrations.AddField(
            model_name="payment",
            name="admin_description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات مدیر"),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار بررسی"),
                    ("verified", "تایید شده"),
                    ("rejected", "رد شده"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.BigIntegerField(verbose_name="مبلغ (ریال)"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="receipt_image",
            field=models.ImageField(upload_to="receipts/", verbose_name="تصویر فیش"),
        ),
    ]
